// More catalog apps. Same fields as apps.js, plus a compact form for single-container apps:
//   image:  the image (instead of a services list)
//   port:   [host, container, extra] -> one "Web UI" port; extra is merged in (e.g. { https: true })
//   ports:  full port list instead of port
//   data:   container path of the app's config folder, mounted from ${CONFIG_ROOT}/<id>
//   volumes, env, user, command, hostNetwork, pid, capAdd, devices, sysctls: as in a service
//   secretFormats: { NAME: "laravel" | "hex64" | <length> } for secrets that need a specific shape
// The compact form is expanded into a normal service by app.js.

APPS.push(
  // ---------- Media ----------
  {
    id: "emby", lxc: "emby", name: "Emby", category: "Media", difficulty: 1, lsio: true, gpu: true,
    desc: "Media server with polished apps. Some features need Emby Premiere.",
    docs: "https://emby.media/support/articles/Home.html",
    image: "lscr.io/linuxserver/emby:latest", port: [8097, 8096], data: "/config",
    volumes: ["${DATA_ROOT}/media:/data/media"],
  },
  {
    id: "photoprism", lxc: "photoprism", name: "PhotoPrism", category: "Media", difficulty: 2,
    desc: "AI-powered photo library: browse, search and organise your pictures.",
    docs: "https://docs.photoprism.app/getting-started/docker-compose/",
    secrets: ["PHOTOPRISM_ADMIN_PASSWORD"],
    note: "Log in as admin with PHOTOPRISM_ADMIN_PASSWORD from .env. Put photos in data/media/photos.",
    image: "photoprism/photoprism:latest", port: [2342, 2342], data: "/photoprism/storage",
    env: {
      PHOTOPRISM_ADMIN_USER: "admin", PHOTOPRISM_ADMIN_PASSWORD: "${PHOTOPRISM_ADMIN_PASSWORD}",
      PHOTOPRISM_AUTH_MODE: "password", PHOTOPRISM_DATABASE_DRIVER: "sqlite",
    },
    volumes: ["${DATA_ROOT}/media/photos:/photoprism/originals"],
  },
  {
    id: "tautulli", lxc: "tautulli", name: "Tautulli", category: "Media", difficulty: 1, lsio: true,
    desc: "Stats, history and notifications for your Plex server.",
    docs: "https://docs.tautulli.com/",
    image: "lscr.io/linuxserver/tautulli:latest", port: [8181, 8181], data: "/config",
  },
  {
    id: "calibreweb", lxc: "calibre-web", name: "Calibre-Web", category: "Media", difficulty: 1, lsio: true,
    desc: "Clean web interface to read and download books from a Calibre library.",
    docs: "https://github.com/janeczku/calibre-web/wiki",
    note: "Needs an existing Calibre library (metadata.db) in data/media/books. Default login: admin / admin123. Change it.",
    image: "lscr.io/linuxserver/calibre-web:latest", port: [8084, 8083], data: "/config",
    volumes: ["${DATA_ROOT}/media/books:/books"],
  },
  {
    id: "calibre", name: "Calibre", category: "Media", difficulty: 2, lsio: true,
    desc: "The full Calibre ebook manager, running in your browser.",
    docs: "https://docs.linuxserver.io/images/docker-calibre/",
    image: "lscr.io/linuxserver/calibre:latest", port: [8106, 8080], data: "/config",
    volumes: ["${DATA_ROOT}/media/books:/books"],
  },
  {
    id: "komga", lxc: "komga", name: "Komga", category: "Media", difficulty: 1,
    desc: "Comics and manga server with a great web reader.",
    docs: "https://komga.org/docs/installation/docker",
    image: "gotson/komga:latest", port: [25600, 25600], data: "/config", user: "${PUID}:${PGID}",
    env: { TZ: "${TZ}" },
    volumes: ["${DATA_ROOT}/media/comics:/data"],
  },
  {
    id: "handbrake", name: "HandBrake", category: "Media", difficulty: 2, gpu: true,
    desc: "Convert and shrink videos from a browser. Drop files in a watch folder to auto-convert.",
    docs: "https://github.com/jlesage/docker-handbrake",
    image: "jlesage/handbrake:latest", port: [5800, 5800], data: "/config",
    env: { USER_ID: "${PUID}", GROUP_ID: "${PGID}", TZ: "${TZ}" },
    volumes: ["${DATA_ROOT}/media:/storage:ro", "${DATA_ROOT}/handbrake/watch:/watch", "${DATA_ROOT}/handbrake/output:/output"],
  },
  {
    id: "owncast", lxc: "owncast", name: "Owncast", category: "Media", difficulty: 2,
    desc: "Your own Twitch-style live streaming server with chat.",
    docs: "https://owncast.online/docs/",
    note: "Admin page is /admin, default password abc123. Change it right away. Stream from OBS to rtmp://<server>:1935/live.",
    image: "owncast/owncast:latest", data: "/app/data",
    ports: [{ host: 8098, container: 8080, label: "Web UI" }, { host: 1935, container: 1935, label: "RTMP ingest" }],
  },
  {
    id: "pinchflat", lxc: "pinchflat", name: "Pinchflat", category: "Media", difficulty: 1,
    desc: "Automatically downloads new videos from YouTube channels you follow.",
    docs: "https://github.com/kieraneglin/pinchflat/wiki",
    image: "keglin/pinchflat:latest", port: [8945, 8945], data: "/config",
    env: { TZ: "${TZ}" },
    volumes: ["${DATA_ROOT}/media/youtube:/downloads"],
  },
  {
    id: "metube", lxc: "metube", name: "MeTube", category: "Media", difficulty: 1,
    desc: "Paste a link, download the video (YouTube and 1000+ sites, via yt-dlp).",
    docs: "https://github.com/alexta69/metube",
    image: "ghcr.io/alexta69/metube:latest", port: [8087, 8081],
    env: { UID: "${PUID}", GID: "${PGID}" },
    volumes: ["${DATA_ROOT}/media/youtube:/downloads"],
  },
  {
    id: "ersatztv", lxc: "ersatztv", name: "ErsatzTV", category: "Media", difficulty: 2,
    desc: "Turn your media library into live TV channels for Plex, Jellyfin or any IPTV player.",
    docs: "https://ersatztv.org/docs/",
    image: "jasongdove/ersatztv:latest", port: [8409, 8409], data: "/config",
    env: { TZ: "${TZ}" },
    volumes: ["${DATA_ROOT}/media:/data/media:ro"],
  },
  {
    id: "maintainerr", lxc: "maintainerr", name: "Maintainerr", category: "Media", difficulty: 2,
    desc: "Cleans up media nobody watches, based on rules you set.",
    docs: "https://docs.maintainerr.info/",
    image: "ghcr.io/maintainerr/maintainerr:latest", port: [6246, 6246], data: "/opt/data", user: "${PUID}:${PGID}",
    env: { TZ: "${TZ}" },
  },
  {
    id: "wizarr", lxc: "wizarr", name: "Wizarr", category: "Media", difficulty: 1,
    desc: "Invite friends to your Jellyfin/Plex with a link and a guided onboarding.",
    docs: "https://docs.wizarr.dev/",
    image: "ghcr.io/wizarrrr/wizarr:latest", port: [5690, 5690], data: "/data/database",
    env: { TZ: "${TZ}" },
  },

  // ---------- Downloads ----------
  {
    id: "ombi", lxc: "ombi", name: "Ombi", category: "Downloads", difficulty: 1, lsio: true,
    desc: "Request portal for Plex/Jellyfin/Emby users, linked to Sonarr and Radarr.",
    docs: "https://docs.ombi.app/",
    image: "lscr.io/linuxserver/ombi:latest", port: [3579, 3579], data: "/config",
  },
  {
    id: "sabnzbd", lxc: "sabnzbd", name: "SABnzbd", category: "Downloads", difficulty: 2, lsio: true,
    desc: "Usenet downloader. Needs a Usenet provider and indexer.",
    docs: "https://sabnzbd.org/wiki/",
    note: "Set the completed folder to /data/usenet/complete so Sonarr/Radarr can import with hardlinks.",
    image: "lscr.io/linuxserver/sabnzbd:latest", port: [8082, 8080], data: "/config",
    volumes: ["${DATA_ROOT}/usenet:/data/usenet"],
  },
  {
    id: "nzbget", lxc: "nzbget", name: "NZBGet", category: "Downloads", difficulty: 2, lsio: true,
    desc: "Fast, lightweight Usenet downloader.",
    docs: "https://nzbget.com/documentation/",
    secrets: ["NZBGET_PASSWORD"],
    note: "Log in as nzbget with NZBGET_PASSWORD from .env.",
    image: "lscr.io/linuxserver/nzbget:latest", port: [6789, 6789], data: "/config",
    env: { NZBGET_USER: "nzbget", NZBGET_PASS: "${NZBGET_PASSWORD}" },
    volumes: ["${DATA_ROOT}/usenet:/data/usenet"],
  },
  {
    id: "transmission", lxc: "transmission", name: "Transmission", category: "Downloads", difficulty: 1, lsio: true, vpn: true,
    desc: "Simple, lightweight torrent client.",
    docs: "https://docs.linuxserver.io/images/docker-transmission/",
    secrets: ["TRANSMISSION_PASSWORD"],
    note: "Log in as admin with TRANSMISSION_PASSWORD from .env.",
    image: "lscr.io/linuxserver/transmission:latest", data: "/config",
    ports: [
      { host: 9091, container: 9091, label: "Web UI" },
      { host: 51413, container: 51413, label: "Peers (TCP)" },
      { host: 51413, container: 51413, proto: "udp", label: "Peers (UDP)" },
    ],
    env: { USER: "admin", PASS: "${TRANSMISSION_PASSWORD}", PEERPORT: "51413" },
    volumes: ["${DATA_ROOT}/torrents:/data/torrents"],
  },
  {
    id: "jackett", lxc: "jackett", name: "Jackett", category: "Downloads", difficulty: 2, lsio: true,
    desc: "Indexer proxy for torrent sites (older alternative to Prowlarr).",
    docs: "https://github.com/Jackett/Jackett",
    image: "lscr.io/linuxserver/jackett:latest", port: [9117, 9117], data: "/config",
  },
  {
    id: "flaresolverr", lxc: "flaresolverr", name: "FlareSolverr", category: "Downloads", difficulty: 2,
    desc: "Gets Prowlarr/Jackett past Cloudflare checks on some indexers.",
    docs: "https://github.com/FlareSolverr/FlareSolverr",
    note: "In Prowlarr, add it under Settings → Indexers as http://flaresolverr:8191.",
    image: "ghcr.io/flaresolverr/flaresolverr:latest", port: [8191, 8191, { label: "API" }],
    env: { TZ: "${TZ}" },
  },
  {
    id: "autobrr", lxc: "autobrr", name: "autobrr", category: "Downloads", difficulty: 3,
    desc: "Grabs torrents from IRC announce channels the moment they're released.",
    docs: "https://autobrr.com/",
    image: "ghcr.io/autobrr/autobrr:latest", port: [7474, 7474], data: "/config", user: "${PUID}:${PGID}",
    env: { TZ: "${TZ}" },
  },

  // ---------- Network & security ----------
  {
    id: "caddy", lxc: "caddy", name: "Caddy", category: "Network", difficulty: 2,
    desc: "Simple reverse proxy with automatic HTTPS, configured with a short text file.",
    docs: "https://caddyserver.com/docs/",
    note: "Create <config folder>/caddy/etc/Caddyfile before starting, e.g.: jellyfin.example.com { reverse_proxy jellyfin:8096 }",
    services: [{
      name: "caddy", image: "caddy:2",
      ports: [
        { host: 80, container: 80, label: "HTTP", fixed: true },
        { host: 443, container: 443, label: "HTTPS", fixed: true },
        { host: 443, container: 443, proto: "udp", label: "HTTP/3", fixed: true },
      ],
      volumes: ["${CONFIG_ROOT}/caddy/etc:/etc/caddy", "${CONFIG_ROOT}/caddy/data:/data", "${CONFIG_ROOT}/caddy/config:/config"],
    }],
  },
  {
    id: "traefik", lxc: "traefik", name: "Traefik", category: "Network", difficulty: 3,
    desc: "Reverse proxy that configures itself from Docker labels.",
    docs: "https://doc.traefik.io/traefik/",
    note: "Add traefik.enable=true and router labels to the services you want to expose. The dashboard has no login. Don't expose it.",
    services: [{
      name: "traefik", image: "traefik:v3",
      command: "--providers.docker=true --providers.docker.exposedbydefault=false --entrypoints.web.address=:80 --entrypoints.websecure.address=:443 --api.dashboard=true --api.insecure=true",
      ports: [
        { host: 80, container: 80, label: "HTTP", fixed: true },
        { host: 443, container: 443, label: "HTTPS", fixed: true },
        { host: 8079, container: 8080, label: "Dashboard UI", path: "/dashboard/" },
      ],
      volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro", "${CONFIG_ROOT}/traefik:/letsencrypt"],
    }],
  },
  {
    id: "authelia", lxc: "authelia", name: "Authelia", category: "Security", difficulty: 3,
    desc: "Single sign-on and two-factor login in front of all your apps.",
    docs: "https://www.authelia.com/integration/prologue/get-started/",
    note: "Needs a configuration.yml in its config folder and a reverse proxy in front. Follow the get-started guide.",
    image: "authelia/authelia:latest", port: [9092, 9091], data: "/config",
    env: { TZ: "${TZ}" },
  },
  {
    id: "authentik", lxc: "authentik", name: "authentik", category: "Security", difficulty: 3,
    desc: "Full identity provider: SSO, OAuth/OIDC, LDAP, user self-service.",
    docs: "https://docs.goauthentik.io/",
    composeUrl: "https://docs.goauthentik.io/install-config/install/docker-compose/",
    note: "Needs PostgreSQL plus a server and worker container. Use the official compose file.",
  },
  {
    id: "crowdsec", name: "CrowdSec", category: "Security", difficulty: 3,
    desc: "Detects attacks in your logs and blocks bad IPs, using community threat data.",
    docs: "https://docs.crowdsec.net/",
    note: "On its own it only detects. Add a bouncer (e.g. for your reverse proxy or firewall) to actually block.",
    image: "crowdsecurity/crowdsec:latest", port: [8099, 8080, { label: "API" }],
    env: { COLLECTIONS: "crowdsecurity/linux crowdsecurity/nginx" },
    volumes: ["${CONFIG_ROOT}/crowdsec/config:/etc/crowdsec", "${CONFIG_ROOT}/crowdsec/data:/var/lib/crowdsec/data", "/var/log:/var/log:ro"],
  },
  {
    id: "unbound", lxc: "unbound", name: "Unbound", category: "Network", difficulty: 3,
    desc: "Your own recursive DNS resolver. Pair with Pi-hole/AdGuard so no DNS company sees your lookups.",
    docs: "https://unbound.docs.nlnetlabs.nl/",
    note: "Set Pi-hole/AdGuard's upstream DNS to <server-ip>#5335 (Pi-hole) or <server-ip>:5335 (AdGuard).",
    image: "mvance/unbound:latest",
    ports: [
      { host: 5335, container: 53, label: "DNS (TCP)" },
      { host: 5335, container: 53, proto: "udp", label: "DNS (UDP)" },
    ],
  },
  {
    id: "cloudflared", lxc: "cloudflared", name: "Cloudflare Tunnel", category: "Network", difficulty: 2,
    desc: "Publish apps on your domain through Cloudflare, with no open ports on your router.",
    docs: "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/",
    note: "Create a tunnel in the Cloudflare Zero Trust dashboard and copy its token. Point public hostnames at http://<service>:<port> (e.g. http://jellyfin:8096).",
    vars: { CLOUDFLARE_TUNNEL_TOKEN: { value: "", help: "Tunnel token from Cloudflare Zero Trust → Networks → Tunnels" } },
    image: "cloudflare/cloudflared:latest", command: "tunnel --no-autoupdate run",
    env: { TUNNEL_TOKEN: "${CLOUDFLARE_TUNNEL_TOKEN}" },
  },
  {
    id: "ddnsupdater", lxc: "ddns-updater", name: "DDNS Updater", category: "Network", difficulty: 2,
    desc: "Keeps your domain pointed at your home IP when it changes (Cloudflare, DuckDNS and 50+ more).",
    docs: "https://github.com/qdm12/ddns-updater",
    note: "Put a config.json with your DNS provider details in its config folder. See the docs for examples.",
    image: "ghcr.io/qdm12/ddns-updater:latest", port: [8001, 8000], data: "/updater/data", user: "${PUID}:${PGID}",
    env: { TZ: "${TZ}" },
  },
  {
    id: "technitium", lxc: "technitiumdns", name: "Technitium DNS", category: "Network", difficulty: 2,
    desc: "Full DNS server with ad blocking, DNS-over-HTTPS and local domains.",
    docs: "https://technitium.com/dns/",
    image: "technitium/dns-server:latest", data: "/etc/dns",
    ports: [
      { host: 53, container: 53, label: "DNS (TCP)", fixed: true },
      { host: 53, container: 53, proto: "udp", label: "DNS (UDP)", fixed: true },
      { host: 5380, container: 5380, label: "Web UI" },
    ],
  },
  {
    id: "twofauth", lxc: "2fauth", name: "2FAuth", category: "Security", difficulty: 1,
    desc: "Keep your two-factor (TOTP) codes in a web app you control.",
    docs: "https://docs.2fauth.app/",
    secrets: ["TWOFAUTH_APP_KEY"], secretFormats: { TWOFAUTH_APP_KEY: 32 },
    note: "The data folder must be owned by user 1000: sudo chown -R 1000:1000 <config folder>/twofauth",
    image: "2fauth/2fauth:latest", port: [8013, 8000], data: "/2fauth",
    env: { APP_KEY: "${TWOFAUTH_APP_KEY}" },
  },

  // ---------- Notifications ----------
  {
    id: "ntfy", lxc: "ntfy", name: "ntfy", category: "Notifications", difficulty: 1,
    desc: "Send push notifications to your phone from any script or app with a simple HTTP call.",
    docs: "https://docs.ntfy.sh/",
    image: "binwiederhier/ntfy:latest", command: "serve", port: [8093, 80],
    env: { TZ: "${TZ}" },
    volumes: ["${CONFIG_ROOT}/ntfy/cache:/var/cache/ntfy", "${CONFIG_ROOT}/ntfy/etc:/etc/ntfy"],
  },
  {
    id: "gotify", lxc: "gotify", name: "Gotify", category: "Notifications", difficulty: 1,
    desc: "Self-hosted push notification server with an Android app.",
    docs: "https://gotify.net/docs/",
    secrets: ["GOTIFY_ADMIN_PASSWORD"],
    note: "Log in as admin with GOTIFY_ADMIN_PASSWORD from .env.",
    image: "gotify/server:latest", port: [8094, 80], data: "/app/data",
    env: { TZ: "${TZ}", GOTIFY_DEFAULTUSER_PASS: "${GOTIFY_ADMIN_PASSWORD}" },
  },

  // ---------- Monitoring ----------
  {
    id: "netdata", name: "Netdata", category: "Monitoring", difficulty: 2,
    lxcAlt: "Or skip Docker: install it on the Proxmox host with the official script from learn.netdata.cloud.",
    desc: "Real-time, per-second monitoring of everything on your server, zero config.",
    docs: "https://learn.netdata.cloud/docs/netdata-agent/installation/docker",
    image: "netdata/netdata:stable", hostNetwork: true, pid: "host", capAdd: ["SYS_PTRACE", "SYS_ADMIN"],
    ports: [{ host: 19999, container: 19999, label: "Web UI" }],
    volumes: [
      "${CONFIG_ROOT}/netdata/config:/etc/netdata", "${CONFIG_ROOT}/netdata/lib:/var/lib/netdata", "${CONFIG_ROOT}/netdata/cache:/var/cache/netdata",
      "/:/host/root:ro,rslave", "/etc/passwd:/host/etc/passwd:ro", "/etc/group:/host/etc/group:ro", "/etc/localtime:/etc/localtime:ro",
      "/proc:/host/proc:ro", "/sys:/host/sys:ro", "/etc/os-release:/host/etc/os-release:ro", "/var/log:/host/var/log:ro",
      "/var/run/docker.sock:/var/run/docker.sock:ro",
    ],
  },
  {
    id: "glances", name: "Glances", category: "Monitoring", difficulty: 1,
    lxcAlt: "Or skip Docker: install it on the Proxmox host with apt install glances.",
    desc: "Lightweight 'top' for your server in the browser: CPU, RAM, disks, containers.",
    docs: "https://glances.readthedocs.io/en/latest/docker.html",
    image: "nicolargo/glances:latest-full", pid: "host", port: [61208, 61208],
    env: { GLANCES_OPT: "-w", TZ: "${TZ}" },
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro", "/etc/os-release:/etc/os-release:ro"],
  },
  {
    id: "beszel", lxc: "beszel", name: "Beszel", category: "Monitoring", difficulty: 2,
    desc: "Simple server monitoring with history, Docker stats and alerts. Watches several machines.",
    docs: "https://beszel.dev/guide/getting-started",
    note: "In the hub, click Add System, copy the public key into BESZEL_AGENT_KEY in .env, use this server's IP and port 45876, then docker compose up -d again.",
    vars: { BESZEL_AGENT_KEY: { value: "", help: "Public key shown in the Beszel hub under Add System" } },
    services: [
      {
        name: "beszel", image: "henrygd/beszel:latest",
        ports: [{ host: 8070, container: 8090, label: "Web UI" }],
        volumes: ["${CONFIG_ROOT}/beszel/data:/beszel_data"],
      },
      {
        name: "beszel-agent", image: "henrygd/beszel-agent:latest", hostNetwork: true,
        ports: [{ host: 45876, container: 45876, label: "Agent" }],
        env: { LISTEN: "45876", KEY: "${BESZEL_AGENT_KEY}" },
        volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro", "${CONFIG_ROOT}/beszel/agent:/var/lib/beszel-agent"],
      },
    ],
  },
  {
    id: "prometheus", lxc: "prometheus", name: "Prometheus", category: "Monitoring", difficulty: 3,
    desc: "Metrics database that scrapes exporters. The usual data source for Grafana.",
    docs: "https://prometheus.io/docs/prometheus/latest/installation/",
    note: "Starts with a default config that only watches itself. Add scrape targets (e.g. Node Exporter at <server-ip>:9100).",
    image: "prom/prometheus:latest", port: [9095, 9090], user: "${PUID}:${PGID}",
    volumes: ["${CONFIG_ROOT}/prometheus/data:/prometheus"],
  },
  {
    id: "nodeexporter", name: "Node Exporter", category: "Monitoring", difficulty: 3,
    lxcAlt: "Or skip Docker: install it on the Proxmox host with apt install prometheus-node-exporter.",
    desc: "Exposes this server's CPU, memory, disk and network metrics for Prometheus.",
    docs: "https://github.com/prometheus/node_exporter",
    image: "prom/node-exporter:latest", hostNetwork: true, pid: "host", command: "--path.rootfs=/host",
    ports: [{ host: 9100, container: 9100, label: "Metrics" }],
    volumes: ["/:/host:ro,rslave"],
  },
  {
    id: "influxdb", lxc: "influxdb", name: "InfluxDB", category: "Monitoring", difficulty: 3,
    desc: "Time-series database for sensor data, Home Assistant history and metrics.",
    docs: "https://docs.influxdata.com/influxdb/v2/install/",
    image: "influxdb:2", port: [8086, 8086],
    volumes: ["${CONFIG_ROOT}/influxdb/data:/var/lib/influxdb2", "${CONFIG_ROOT}/influxdb/config:/etc/influxdb2"],
  },
  {
    id: "healthchecks", lxc: "healthchecks", name: "Healthchecks", category: "Monitoring", difficulty: 2, lsio: true,
    desc: "Alerts you when your cron jobs and backups don't check in on time.",
    docs: "https://healthchecks.io/docs/self_hosted_docker/",
    secrets: ["HEALTHCHECKS_PASSWORD"],
    vars: {
      HEALTHCHECKS_SITE_ROOT: { value: "http://your-server-ip:8002", help: "The address you'll open Healthchecks at" },
      HEALTHCHECKS_EMAIL: { value: "admin@example.com", help: "Your login email" },
    },
    note: "Log in with HEALTHCHECKS_EMAIL and HEALTHCHECKS_PASSWORD from .env.",
    image: "lscr.io/linuxserver/healthchecks:latest", port: [8002, 8000], data: "/config",
    env: { SITE_ROOT: "${HEALTHCHECKS_SITE_ROOT}", SUPERUSER_EMAIL: "${HEALTHCHECKS_EMAIL}", SUPERUSER_PASSWORD: "${HEALTHCHECKS_PASSWORD}" },
  },
  {
    id: "speedtest", lxc: "speedtest-tracker", name: "Speedtest Tracker", category: "Monitoring", difficulty: 1, lsio: true,
    desc: "Runs internet speed tests on a schedule and graphs the history.",
    docs: "https://docs.speedtest-tracker.dev/",
    secrets: ["SPEEDTEST_APP_KEY"], secretFormats: { SPEEDTEST_APP_KEY: "laravel" },
    note: "Default login: admin@example.com / password. Change it after logging in.",
    image: "lscr.io/linuxserver/speedtest-tracker:latest", port: [8765, 80], data: "/config",
    env: { APP_KEY: "${SPEEDTEST_APP_KEY}", DB_CONNECTION: "sqlite", SPEEDTEST_SCHEDULE: "0 */6 * * *" },
  },
  {
    id: "librespeed", lxc: "librespeed-rust", name: "LibreSpeed", category: "Monitoring", difficulty: 1, lsio: true,
    desc: "Speed test page for your own network: check Wi-Fi and LAN speed to the server.",
    docs: "https://docs.linuxserver.io/images/docker-librespeed/",
    image: "lscr.io/linuxserver/librespeed:latest", port: [8091, 80], data: "/config",
  },
  {
    id: "smokeping", lxc: "smokeping", name: "SmokePing", category: "Monitoring", difficulty: 2, lsio: true,
    desc: "Graphs latency and packet loss over time to spot a flaky connection.",
    docs: "https://docs.linuxserver.io/images/docker-smokeping/",
    image: "lscr.io/linuxserver/smokeping:latest", port: [8089, 80], data: "/config",
    volumes: ["${CONFIG_ROOT}/smokeping-data:/data"],
  },
  {
    id: "changedetection", lxc: "changedetection", name: "changedetection.io", category: "Monitoring", difficulty: 1,
    desc: "Watches web pages and alerts you when they change (prices, restocks, news).",
    docs: "https://changedetection.io/tutorials",
    image: "ghcr.io/dgtlmoon/changedetection.io:latest", port: [5001, 5000], data: "/datastore",
  },

  // ---------- Management ----------
  {
    id: "dockge", lxc: "dockge", name: "Dockge", category: "Management", difficulty: 1,
    desc: "Friendly web UI for managing docker-compose stacks.",
    docs: "https://github.com/louislam/dockge",
    note: "Stacks live in /opt/stacks on the server. Paste your generated compose file in as a new stack.",
    image: "louislam/dockge:1", port: [5003, 5001], data: "/app/data",
    env: { DOCKGE_STACKS_DIR: "/opt/stacks" },
    volumes: ["/var/run/docker.sock:/var/run/docker.sock", "/opt/stacks:/opt/stacks"],
  },
  {
    id: "wud", name: "What's up Docker", category: "Management", difficulty: 1,
    lxcAlt: "Only useful if you run Docker.",
    desc: "Shows which of your containers have newer images available.",
    docs: "https://getwud.github.io/wud/",
    image: "getwud/wud:latest", port: [3005, 3000],
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
  },
  {
    id: "homarr", lxc: "homarr", name: "Homarr", category: "Management", difficulty: 1,
    desc: "Drag-and-drop dashboard with app integrations, configured in the browser.",
    docs: "https://homarr.dev/docs/getting-started/installation/docker",
    secrets: ["HOMARR_SECRET_KEY"], secretFormats: { HOMARR_SECRET_KEY: "hex64" },
    image: "ghcr.io/homarr-labs/homarr:latest", port: [7575, 7575], data: "/appdata",
    env: { SECRET_ENCRYPTION_KEY: "${HOMARR_SECRET_KEY}" },
    volumes: ["/var/run/docker.sock:/var/run/docker.sock:ro"],
  },
  {
    id: "heimdall", lxc: "heimdall-dashboard", name: "Heimdall", category: "Management", difficulty: 1, lsio: true,
    desc: "Simple, pretty start page with tiles for all your apps.",
    docs: "https://docs.linuxserver.io/images/docker-heimdall/",
    image: "lscr.io/linuxserver/heimdall:latest", port: [8095, 80], data: "/config",
  },
  {
    id: "homer", lxc: "homer", name: "Homer", category: "Management", difficulty: 1,
    desc: "Static, super-fast start page configured with one YAML file.",
    docs: "https://github.com/bastienwirtz/homer",
    image: "b4bz/homer:latest", port: [8100, 8080], data: "/www/assets", user: "${PUID}:${PGID}",
    env: { INIT_ASSETS: "1" },
  },

  // ---------- Notes, wikis & docs ----------
  {
    id: "bookstack", lxc: "bookstack", name: "BookStack", category: "Notes & Wiki", difficulty: 2, lsio: true,
    desc: "Easy wiki organised like books, chapters and pages.",
    docs: "https://www.bookstackapp.com/docs/",
    secrets: ["BOOKSTACK_APP_KEY", "BOOKSTACK_DB_PASSWORD", "BOOKSTACK_DB_ROOT_PASSWORD"],
    secretFormats: { BOOKSTACK_APP_KEY: "laravel" },
    vars: { BOOKSTACK_URL: { value: "http://your-server-ip:6875", help: "The exact address you'll open BookStack at" } },
    note: "Default login: admin@admin.com / password. Change it right away. Set BOOKSTACK_URL in .env first.",
    services: [
      {
        name: "bookstack", image: "lscr.io/linuxserver/bookstack:latest",
        ports: [{ host: 6875, container: 80, label: "Web UI" }],
        env: {
          APP_URL: "${BOOKSTACK_URL}", APP_KEY: "${BOOKSTACK_APP_KEY}", DB_HOST: "bookstack-db", DB_PORT: "3306",
          DB_DATABASE: "bookstack", DB_USERNAME: "bookstack", DB_PASSWORD: "${BOOKSTACK_DB_PASSWORD}",
        },
        volumes: ["${CONFIG_ROOT}/bookstack/config:/config"],
        depends: ["bookstack-db"],
      },
      {
        name: "bookstack-db", image: "mariadb:11",
        env: {
          MARIADB_ROOT_PASSWORD: "${BOOKSTACK_DB_ROOT_PASSWORD}", MARIADB_DATABASE: "bookstack",
          MARIADB_USER: "bookstack", MARIADB_PASSWORD: "${BOOKSTACK_DB_PASSWORD}",
        },
        volumes: ["${CONFIG_ROOT}/bookstack/db:/var/lib/mysql"],
      },
    ],
  },
  {
    id: "wikijs", lxc: "wikijs", name: "Wiki.js", category: "Notes & Wiki", difficulty: 2,
    desc: "Modern, good-looking wiki with Markdown and a visual editor.",
    docs: "https://docs.requarks.io/",
    note: "Runs as user 1000: sudo chown -R 1000:1000 <config folder>/wikijs. Uses SQLite here; fine for personal use.",
    image: "ghcr.io/requarks/wiki:2", port: [3006, 3000], data: "/wiki/data",
    env: { DB_TYPE: "sqlite", DB_FILEPATH: "/wiki/data/db.sqlite" },
  },
  {
    id: "outline", lxc: "outline", name: "Outline", category: "Notes & Wiki", difficulty: 3,
    desc: "Fast, beautiful team knowledge base (a Notion/Confluence alternative).",
    docs: "https://docs.getoutline.com/s/hosting",
    composeUrl: "https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t",
    note: "Needs PostgreSQL, Redis and an SSO provider for logins. Use the official guide.",
  },
  {
    id: "trilium", lxc: "trilium", name: "Trilium Notes", category: "Notes & Wiki", difficulty: 1,
    desc: "Hierarchical note-taking app for building a large personal knowledge base.",
    docs: "https://docs.triliumnotes.org/",
    image: "triliumnext/trilium:latest", port: [8180, 8080], data: "/home/node/trilium-data",
    env: { TZ: "${TZ}" },
  },
  {
    id: "joplin", lxc: "joplin-server", name: "Joplin Server", category: "Notes & Wiki", difficulty: 2,
    desc: "Sync server for the Joplin notes apps on desktop and phone.",
    docs: "https://joplinapp.org/help/apps/sync/joplin_server/",
    secrets: ["JOPLIN_DB_PASSWORD"],
    vars: { JOPLIN_URL: { value: "http://your-server-ip:22300", help: "The exact address your Joplin apps will sync to" } },
    note: "Default login: admin@localhost / admin. Change it right away.",
    services: [
      {
        name: "joplin", image: "joplin/server:latest",
        ports: [{ host: 22300, container: 22300, label: "Web UI" }],
        env: {
          APP_PORT: "22300", APP_BASE_URL: "${JOPLIN_URL}", DB_CLIENT: "pg", POSTGRES_HOST: "joplin-db", POSTGRES_PORT: "5432",
          POSTGRES_DATABASE: "joplin", POSTGRES_USER: "joplin", POSTGRES_PASSWORD: "${JOPLIN_DB_PASSWORD}",
        },
        depends: ["joplin-db"],
      },
      {
        name: "joplin-db", image: "postgres:17",
        env: { POSTGRES_DB: "joplin", POSTGRES_USER: "joplin", POSTGRES_PASSWORD: "${JOPLIN_DB_PASSWORD}" },
        volumes: ["${CONFIG_ROOT}/joplin/db:/var/lib/postgresql/data"],
      },
    ],
  },
  {
    id: "memos", lxc: "memos", name: "Memos", category: "Notes & Wiki", difficulty: 1,
    desc: "Quick notes and thoughts in a Twitter-like timeline, just for you.",
    docs: "https://www.usememos.com/docs",
    image: "neosmemo/memos:stable", port: [5230, 5230], data: "/var/opt/memos",
  },
  {
    id: "silverbullet", lxc: "silverbullet", name: "SilverBullet", category: "Notes & Wiki", difficulty: 1,
    desc: "Markdown notes in plain files, with links and live queries. Works offline.",
    docs: "https://silverbullet.md/",
    secrets: ["SILVERBULLET_PASSWORD"],
    note: "Log in as admin with SILVERBULLET_PASSWORD from .env.",
    image: "ghcr.io/silverbulletmd/silverbullet:latest", port: [3007, 3000], data: "/space",
    env: { SB_USER: "admin:${SILVERBULLET_PASSWORD}" },
  },
  {
    id: "couchdb", lxc: "obsidian-livesync", name: "Obsidian LiveSync (CouchDB)", category: "Notes & Wiki", difficulty: 3,
    desc: "Database server for the Obsidian Self-hosted LiveSync plugin: sync your vault yourself.",
    docs: "https://github.com/vrtmrz/obsidian-livesync",
    secrets: ["COUCHDB_PASSWORD"],
    note: "Log in as admin with COUCHDB_PASSWORD. Use the plugin's setup wizard to configure CouchDB. Phones need HTTPS.",
    image: "couchdb:3", port: [5984, 5984, { path: "/_utils" }],
    env: { COUCHDB_USER: "admin", COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}" },
    volumes: ["${CONFIG_ROOT}/couchdb:/opt/couchdb/data"],
  },
  {
    id: "etherpad", lxc: "etherpad", name: "Etherpad", category: "Notes & Wiki", difficulty: 1,
    desc: "Real-time collaborative text editing, like a shared Google Doc.",
    docs: "https://docs.etherpad.org/",
    secrets: ["ETHERPAD_ADMIN_PASSWORD"],
    image: "etherpad/etherpad:latest", port: [9001, 9001], data: "/opt/etherpad-lite/var",
    env: { ADMIN_PASSWORD: "${ETHERPAD_ADMIN_PASSWORD}" },
  },

  // ---------- Productivity ----------
  {
    id: "excalidraw", lxc: "excalidraw", name: "Excalidraw", category: "Productivity", difficulty: 1,
    desc: "Hand-drawn style whiteboard for sketches and diagrams.",
    docs: "https://github.com/excalidraw/excalidraw",
    image: "excalidraw/excalidraw:latest", port: [3008, 80],
  },
  {
    id: "drawio", lxc: "drawio", name: "draw.io", category: "Productivity", difficulty: 1,
    desc: "Flowcharts, network diagrams and org charts in the browser.",
    docs: "https://github.com/jgraph/docker-drawio",
    image: "jgraph/drawio:latest", port: [8101, 8080],
  },
  {
    id: "vikunja", lxc: "vikunja", name: "Vikunja", category: "Productivity", difficulty: 1,
    desc: "To-do lists, kanban boards and Gantt charts (a Todoist/Trello alternative).",
    docs: "https://vikunja.io/docs/",
    secrets: ["VIKUNJA_JWT_SECRET"],
    vars: { VIKUNJA_URL: { value: "http://your-server-ip:3456/", help: "The exact address you'll open Vikunja at" } },
    note: "Runs as user 1000: sudo chown -R 1000:1000 <config folder>/vikunja. Register your account on first visit.",
    image: "vikunja/vikunja:latest", port: [3456, 3456],
    env: { VIKUNJA_SERVICE_PUBLICURL: "${VIKUNJA_URL}", VIKUNJA_SERVICE_JWTSECRET: "${VIKUNJA_JWT_SECRET}", VIKUNJA_DATABASE_PATH: "/db/vikunja.db" },
    volumes: ["${CONFIG_ROOT}/vikunja/files:/app/vikunja/files", "${CONFIG_ROOT}/vikunja/db:/db"],
  },
  {
    id: "kanboard", name: "Kanboard", category: "Productivity", difficulty: 1,
    desc: "Minimal kanban board for personal or small-team projects.",
    docs: "https://docs.kanboard.org/",
    note: "Default login: admin / admin. Change it right away.",
    image: "kanboard/kanboard:latest", port: [8112, 80],
    volumes: ["${CONFIG_ROOT}/kanboard/data:/var/www/app/data", "${CONFIG_ROOT}/kanboard/plugins:/var/www/app/plugins"],
  },
  {
    id: "planka", lxc: "planka", name: "Planka", category: "Productivity", difficulty: 2,
    desc: "Trello-style boards with real-time collaboration.",
    docs: "https://docs.planka.cloud/",
    composeUrl: "https://docs.planka.cloud/docs/installation/docker/production-version",
    note: "Needs PostgreSQL. Use the official compose file.",
  },
  {
    id: "affine", lxc: "affine", name: "AFFiNE", category: "Productivity", difficulty: 2,
    desc: "Docs, whiteboards and databases in one (a Notion + Miro alternative).",
    docs: "https://docs.affine.pro/",
    composeUrl: "https://docs.affine.pro/self-host-affine",
    note: "Needs PostgreSQL and Redis. Use the official compose file.",
  },
  {
    id: "radicale", lxc: "radicale", name: "Radicale", category: "Productivity", difficulty: 2,
    desc: "Tiny calendar and contacts server (CalDAV/CardDAV) for phones and Thunderbird.",
    docs: "https://radicale.org/v3.html",
    note: "Add users with an htpasswd file in its config folder. See the image's README.",
    image: "tomsquest/docker-radicale:latest", port: [5232, 5232], data: "/data",
    volumes: ["${CONFIG_ROOT}/radicale-config:/config:ro"],
  },
  {
    id: "baikal", lxc: "baikal", name: "Baïkal", category: "Productivity", difficulty: 1,
    desc: "Calendar and contacts server (CalDAV/CardDAV) with a web admin page.",
    docs: "https://sabre.io/baikal/",
    note: "Open the web UI to run the setup wizard and create users.",
    image: "ckulka/baikal:nginx", port: [8113, 80],
    volumes: ["${CONFIG_ROOT}/baikal/config:/var/www/baikal/config", "${CONFIG_ROOT}/baikal/data:/var/www/baikal/Specific"],
  },
  {
    id: "docuseal", lxc: "docuseal", name: "DocuSeal", category: "Productivity", difficulty: 1,
    desc: "Create, fill and sign documents online (a DocuSign alternative).",
    docs: "https://www.docuseal.com/docs",
    image: "docuseal/docuseal:latest", port: [3010, 3000], data: "/data",
  },
  {
    id: "ittools", lxc: "alpine-it-tools", name: "IT-Tools", category: "Productivity", difficulty: 1,
    desc: "80+ handy developer tools: converters, generators, encoders, network calculators.",
    docs: "https://github.com/CorentinTh/it-tools",
    image: "corentinth/it-tools:latest", port: [8102, 80],
  },
  {
    id: "cyberchef", lxc: "cyberchef", name: "CyberChef", category: "Productivity", difficulty: 1,
    desc: "The 'Cyber Swiss Army Knife' for encoding, decoding and analysing data.",
    docs: "https://github.com/gchq/CyberChef",
    image: "ghcr.io/gchq/cyberchef:latest", port: [8103, 80],
  },
  {
    id: "privatebin", lxc: "privatebin", name: "PrivateBin", category: "Productivity", difficulty: 1,
    desc: "Encrypted pastebin: share text that the server itself can't read.",
    docs: "https://github.com/PrivateBin/docker-nginx-fpm-alpine",
    note: "Its data folder must be owned by user 65534: sudo chown -R 65534:82 <config folder>/privatebin",
    image: "privatebin/nginx-fpm-alpine:latest", port: [8104, 8080], data: "/srv/data",
  },
  {
    id: "pairdrop", lxc: "pairdrop", name: "PairDrop", category: "Productivity", difficulty: 1, lsio: true,
    desc: "AirDrop for every device: send files between phones and computers on your network.",
    docs: "https://github.com/schlagmichdoch/PairDrop",
    image: "lscr.io/linuxserver/pairdrop:latest", port: [3009, 3000],
  },
  {
    id: "filebrowser", name: "File Browser", category: "Productivity", difficulty: 1,
    desc: "Browse, upload, share and edit the files on your server from a browser.",
    docs: "https://filebrowser.org/",
    note: "Shows your data folder. The admin password is printed in the logs on first start: docker logs filebrowser",
    image: "filebrowser/filebrowser:latest", port: [8105, 80], user: "${PUID}:${PGID}",
    volumes: ["${DATA_ROOT}:/srv", "${CONFIG_ROOT}/filebrowser/database:/database", "${CONFIG_ROOT}/filebrowser/config:/config"],
  },
  {
    id: "seafile", name: "Seafile", category: "Productivity", difficulty: 2,
    desc: "Fast file sync and share, focused on doing files really well.",
    docs: "https://manual.seafile.com/",
    composeUrl: "https://manual.seafile.com/latest/setup/setup_ce_by_docker/",
    note: "Needs MariaDB and memcached. Use the official compose files.",
  },
  {
    id: "libretranslate", lxc: "libretranslate", name: "LibreTranslate", category: "AI", difficulty: 2,
    desc: "Private machine translation API and web page (a Google Translate alternative).",
    docs: "https://docs.libretranslate.com/",
    note: "The first start downloads language models and takes a while. Edit LT_LOAD_ONLY to choose languages.",
    image: "libretranslate/libretranslate:latest", port: [5004, 5000], data: "/home/libretranslate/.local",
    env: { LT_LOAD_ONLY: "en,es,fr,de" },
  },

  // ---------- Bookmarks & reading ----------
  {
    id: "wallabag", lxc: "wallabag", name: "wallabag", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Save articles to read later, without ads (a Pocket alternative).",
    docs: "https://doc.wallabag.org/",
    vars: { WALLABAG_URL: { value: "http://your-server-ip:8110", help: "The exact address you'll open wallabag at" } },
    note: "Default login: wallabag / wallabag. Change it right away.",
    image: "wallabag/wallabag:latest", port: [8110, 80],
    env: { SYMFONY__ENV__DOMAIN_NAME: "${WALLABAG_URL}" },
    volumes: ["${CONFIG_ROOT}/wallabag/data:/var/www/wallabag/data", "${CONFIG_ROOT}/wallabag/images:/var/www/wallabag/web/assets/images"],
  },
  {
    id: "readeck", lxc: "readeck", name: "Readeck", category: "Bookmarks & Reading", difficulty: 1,
    desc: "Clean read-later app that saves full articles, with highlights and ebooks export.",
    docs: "https://readeck.org/en/docs/",
    image: "codeberg.org/readeck/readeck:latest", port: [8111, 8000], data: "/readeck",
  },
  {
    id: "linkwarden", lxc: "linkwarden", name: "Linkwarden", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Collaborative bookmarks that also archive a copy of each page.",
    docs: "https://docs.linkwarden.app/",
    composeUrl: "https://docs.linkwarden.app/self-hosting/installation",
    note: "Needs PostgreSQL and Meilisearch. Use the official compose file.",
  },
  {
    id: "karakeep", lxc: "karakeep", name: "Karakeep", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Bookmark everything (links, notes, images) with AI auto-tagging.",
    docs: "https://docs.karakeep.app/",
    composeUrl: "https://docs.karakeep.app/installation/docker",
    note: "Needs Meilisearch and a headless Chrome container. Use the official compose file.",
  },
  {
    id: "miniflux", lxc: "miniflux", name: "Miniflux", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Minimalist, very fast RSS reader.",
    docs: "https://miniflux.app/docs/",
    secrets: ["MINIFLUX_DB_PASSWORD", "MINIFLUX_ADMIN_PASSWORD"],
    note: "Log in as admin with MINIFLUX_ADMIN_PASSWORD from .env.",
    services: [
      {
        name: "miniflux", image: "miniflux/miniflux:latest",
        ports: [{ host: 8116, container: 8080, label: "Web UI" }],
        env: {
          DATABASE_URL: "postgres://miniflux:${MINIFLUX_DB_PASSWORD}@miniflux-db/miniflux?sslmode=disable",
          RUN_MIGRATIONS: "1", CREATE_ADMIN: "1", ADMIN_USERNAME: "admin", ADMIN_PASSWORD: "${MINIFLUX_ADMIN_PASSWORD}",
        },
        depends: ["miniflux-db"],
      },
      {
        name: "miniflux-db", image: "postgres:17",
        env: { POSTGRES_DB: "miniflux", POSTGRES_USER: "miniflux", POSTGRES_PASSWORD: "${MINIFLUX_DB_PASSWORD}" },
        volumes: ["${CONFIG_ROOT}/miniflux/db:/var/lib/postgresql/data"],
      },
    ],
  },
  {
    id: "archivebox", lxc: "archivebox", name: "ArchiveBox", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Saves full copies of web pages (HTML, PDF, screenshot, media) so they never disappear.",
    docs: "https://github.com/ArchiveBox/ArchiveBox/wiki/Docker",
    secrets: ["ARCHIVEBOX_PASSWORD"],
    note: "Log in as admin with ARCHIVEBOX_PASSWORD from .env.",
    image: "archivebox/archivebox:latest", port: [8125, 8000], data: "/data",
    env: { ADMIN_USERNAME: "admin", ADMIN_PASSWORD: "${ARCHIVEBOX_PASSWORD}" },
  },
  {
    id: "kiwix", lxc: "kiwix", name: "Kiwix", category: "Bookmarks & Reading", difficulty: 2,
    desc: "Offline Wikipedia, Stack Overflow, Project Gutenberg and more.",
    docs: "https://wiki.kiwix.org/wiki/Kiwix-serve",
    note: "Download .zim files from library.kiwix.org into data/zim before starting. It won't start without at least one.",
    image: "ghcr.io/kiwix/kiwix-serve:latest", port: [8124, 8080], command: "*.zim",
    volumes: ["${DATA_ROOT}/zim:/data"],
  },

  // ---------- Finance & home ----------
  {
    id: "firefly", lxc: "firefly", name: "Firefly III", category: "Finance", difficulty: 2,
    desc: "Detailed personal finance manager: accounts, budgets, rules and reports.",
    docs: "https://docs.firefly-iii.org/",
    secrets: ["FIREFLY_APP_KEY", "FIREFLY_DB_PASSWORD", "FIREFLY_DB_ROOT_PASSWORD"],
    secretFormats: { FIREFLY_APP_KEY: 32 },
    services: [
      {
        name: "firefly", image: "fireflyiii/core:latest",
        ports: [{ host: 8107, container: 8080, label: "Web UI" }],
        env: {
          APP_KEY: "${FIREFLY_APP_KEY}", TZ: "${TZ}", TRUSTED_PROXIES: "**", DB_CONNECTION: "mysql", DB_HOST: "firefly-db",
          DB_PORT: "3306", DB_DATABASE: "firefly", DB_USERNAME: "firefly", DB_PASSWORD: "${FIREFLY_DB_PASSWORD}",
        },
        volumes: ["${CONFIG_ROOT}/firefly/upload:/var/www/html/storage/upload"],
        depends: ["firefly-db"],
      },
      {
        name: "firefly-db", image: "mariadb:11",
        env: {
          MARIADB_ROOT_PASSWORD: "${FIREFLY_DB_ROOT_PASSWORD}", MARIADB_DATABASE: "firefly",
          MARIADB_USER: "firefly", MARIADB_PASSWORD: "${FIREFLY_DB_PASSWORD}",
        },
        volumes: ["${CONFIG_ROOT}/firefly/db:/var/lib/mysql"],
      },
    ],
  },
  {
    id: "ghostfolio", lxc: "ghostfolio", name: "Ghostfolio", category: "Finance", difficulty: 2,
    desc: "Track your investments and net worth across brokers.",
    docs: "https://github.com/ghostfolio/ghostfolio",
    composeUrl: "https://github.com/ghostfolio/ghostfolio#run-with-docker-compose",
    note: "Needs PostgreSQL and Redis. Use the official compose file.",
  },
  {
    id: "wallos", lxc: "wallos", name: "Wallos", category: "Finance", difficulty: 1,
    desc: "Track your subscriptions and what they cost per month.",
    docs: "https://github.com/ellite/Wallos",
    image: "bellamy/wallos:latest", port: [8108, 80],
    env: { TZ: "${TZ}" },
    volumes: ["${CONFIG_ROOT}/wallos/db:/var/www/html/db", "${CONFIG_ROOT}/wallos/logos:/var/www/html/images/uploads/logos"],
  },
  {
    id: "grocy", lxc: "grocy", name: "Grocy", category: "Home", difficulty: 1, lsio: true,
    desc: "Groceries and household management: stock, shopping lists, chores, recipes.",
    docs: "https://grocy.info/",
    note: "Default login: admin / admin. Change it right away.",
    image: "lscr.io/linuxserver/grocy:latest", port: [9283, 80], data: "/config",
  },
  {
    id: "kitchenowl", lxc: "kitchenowl", name: "KitchenOwl", category: "Home", difficulty: 1,
    desc: "Shared grocery list and recipe app for the household, with mobile apps.",
    docs: "https://docs.kitchenowl.org/",
    secrets: ["KITCHENOWL_JWT_SECRET"],
    image: "tombursch/kitchenowl:latest", port: [8109, 8080], data: "/data",
    env: { JWT_SECRET_KEY: "${KITCHENOWL_JWT_SECRET}" },
  },
  {
    id: "tandoor", lxc: "tandoor", name: "Tandoor Recipes", category: "Home", difficulty: 2,
    desc: "Recipe manager with meal plans, shopping lists and nutrition.",
    docs: "https://docs.tandoor.dev/",
    composeUrl: "https://docs.tandoor.dev/install/docker/",
    note: "Needs PostgreSQL. Use the official compose file.",
  },
  {
    id: "homebox", lxc: "homebox", name: "HomeBox", category: "Home", difficulty: 1,
    desc: "Home inventory: track what you own, where it is, warranties and receipts.",
    docs: "https://homebox.software/",
    image: "ghcr.io/sysadminsmedia/homebox:latest", port: [3100, 7745], data: "/data",
    env: { TZ: "${TZ}" },
  },
  {
    id: "traccar", lxc: "traccar", name: "Traccar", category: "Home", difficulty: 2,
    desc: "GPS tracking for phones, cars and trackers, with history and geofences.",
    docs: "https://www.traccar.org/documentation/",
    note: "Point the Traccar Client app at <server-ip>:5056.",
    image: "traccar/traccar:latest",
    ports: [{ host: 8126, container: 8082, label: "Web UI" }, { host: 5056, container: 5055, label: "Phone app (OsmAnd)" }],
    volumes: ["${CONFIG_ROOT}/traccar/data:/opt/traccar/data", "${CONFIG_ROOT}/traccar/logs:/opt/traccar/logs"],
  },

  // ---------- Communication ----------
  {
    id: "mattermost", lxc: "mattermost", name: "Mattermost", category: "Communication", difficulty: 2,
    desc: "Team chat with channels and threads (a Slack alternative).",
    docs: "https://docs.mattermost.com/",
    composeUrl: "https://docs.mattermost.com/deployment-guide/server/containers/install-docker.html",
    note: "Needs PostgreSQL and specific folder permissions. Use the official guide.",
  },
  {
    id: "synapse", lxc: "elementsynapse", name: "Matrix (Synapse)", category: "Communication", difficulty: 3,
    desc: "Your own Matrix chat server: end-to-end encrypted, federated, bridges to other apps.",
    docs: "https://element-hq.github.io/synapse/latest/",
    composeUrl: "https://element-hq.github.io/synapse/latest/setup/installation.html",
    note: "Needs a domain, HTTPS and config generation. Follow the official guide.",
  },
  {
    id: "gotosocial", name: "GoToSocial", category: "Communication", difficulty: 3,
    desc: "Lightweight Fediverse (Mastodon-compatible) server for you and a few friends.",
    docs: "https://docs.gotosocial.org/",
    vars: { GTS_HOST: { value: "social.example.com", help: "Your domain. Can't be changed later!" } },
    note: "Needs a domain and HTTPS reverse proxy. Create a user with: docker exec -it gotosocial /gotosocial/gotosocial admin account create ...",
    image: "superseriousbusiness/gotosocial:latest", port: [8114, 8080], data: "/gotosocial/storage",
    env: { GTS_HOST: "${GTS_HOST}", GTS_DB_TYPE: "sqlite", GTS_DB_ADDRESS: "/gotosocial/storage/sqlite.db", GTS_LETSENCRYPT_ENABLED: "false", TZ: "${TZ}" },
  },
  {
    id: "thelounge", lxc: "the-lounge", name: "The Lounge", category: "Communication", difficulty: 1, lsio: true,
    desc: "Always-connected IRC client in your browser.",
    docs: "https://thelounge.chat/docs",
    note: "Create a user with: docker exec -it thelounge s6-setuidgid abc thelounge add <name>",
    image: "lscr.io/linuxserver/thelounge:latest", port: [9010, 9000], data: "/config",
  },
  {
    id: "mumble", lxc: "mumble", name: "Mumble", category: "Communication", difficulty: 2,
    desc: "Low-latency voice chat server for gaming groups.",
    docs: "https://github.com/mumble-voip/mumble-docker",
    secrets: ["MUMBLE_SUPERUSER_PASSWORD"],
    image: "mumblevoip/mumble-server:latest", data: "/data",
    ports: [
      { host: 64738, container: 64738, label: "Voice (TCP)" },
      { host: 64738, container: 64738, proto: "udp", label: "Voice (UDP)" },
    ],
    env: { MUMBLE_SUPERUSER_PASSWORD: "${MUMBLE_SUPERUSER_PASSWORD}" },
  },
  {
    id: "teamspeak", lxc: "teamspeak-server", name: "TeamSpeak 3", category: "Communication", difficulty: 2,
    desc: "Classic voice chat server for gaming.",
    docs: "https://hub.docker.com/_/teamspeak",
    note: "The admin privilege key is printed in the logs on first start: docker logs teamspeak",
    image: "teamspeak:latest", data: "/var/ts3server",
    ports: [
      { host: 9987, container: 9987, proto: "udp", label: "Voice" },
      { host: 10011, container: 10011, label: "Server query" },
      { host: 30033, container: 30033, label: "File transfer" },
    ],
    env: { TS3SERVER_LICENSE: "accept" },
  },

  // ---------- Web ----------
  {
    id: "wordpress", lxc: "wordpress", name: "WordPress", category: "Web", difficulty: 1,
    desc: "The world's most popular website and blog platform.",
    docs: "https://hub.docker.com/_/wordpress",
    secrets: ["WORDPRESS_DB_PASSWORD"],
    services: [
      {
        name: "wordpress", image: "wordpress:latest",
        ports: [{ host: 8115, container: 80, label: "Web UI" }],
        env: {
          WORDPRESS_DB_HOST: "wordpress-db", WORDPRESS_DB_USER: "wordpress",
          WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}", WORDPRESS_DB_NAME: "wordpress",
        },
        volumes: ["${CONFIG_ROOT}/wordpress/html:/var/www/html"],
        depends: ["wordpress-db"],
      },
      {
        name: "wordpress-db", image: "mariadb:11",
        env: {
          MARIADB_RANDOM_ROOT_PASSWORD: "1", MARIADB_DATABASE: "wordpress",
          MARIADB_USER: "wordpress", MARIADB_PASSWORD: "${WORDPRESS_DB_PASSWORD}",
        },
        volumes: ["${CONFIG_ROOT}/wordpress/db:/var/lib/mysql"],
      },
    ],
  },
  {
    id: "ghost", name: "Ghost", category: "Web", difficulty: 2,
    desc: "Beautiful publishing platform for blogs and newsletters.",
    docs: "https://ghost.org/docs/",
    secrets: ["GHOST_DB_PASSWORD"],
    vars: { GHOST_URL: { value: "http://your-server-ip:2368", help: "Your blog's public address (e.g. https://blog.example.com)" } },
    note: "Create your admin account at <url>/ghost.",
    services: [
      {
        name: "ghost", image: "ghost:latest",
        ports: [{ host: 2368, container: 2368, label: "Web UI" }],
        env: {
          url: "${GHOST_URL}", database__client: "mysql", database__connection__host: "ghost-db",
          database__connection__user: "root", database__connection__password: "${GHOST_DB_PASSWORD}", database__connection__database: "ghost",
        },
        volumes: ["${CONFIG_ROOT}/ghost/content:/var/lib/ghost/content"],
        depends: ["ghost-db"],
      },
      {
        name: "ghost-db", image: "mysql:8",
        env: { MYSQL_ROOT_PASSWORD: "${GHOST_DB_PASSWORD}", MYSQL_DATABASE: "ghost" },
        volumes: ["${CONFIG_ROOT}/ghost/db:/var/lib/mysql"],
      },
    ],
  },
  {
    id: "nginx", name: "Nginx (static site)", category: "Web", difficulty: 1,
    desc: "Host a simple static website. Drop your HTML files in a folder.",
    docs: "https://hub.docker.com/_/nginx",
    note: "Put your site's files in <config folder>/nginx/html.",
    image: "nginx:alpine", port: [8088, 80],
    volumes: ["${CONFIG_ROOT}/nginx/html:/usr/share/nginx/html:ro"],
  },

  // ---------- Dev ----------
  {
    id: "codeserver", name: "code-server", category: "Dev", difficulty: 1, lsio: true,
    desc: "VS Code in your browser, running on your server.",
    docs: "https://docs.linuxserver.io/images/docker-code-server/",
    secrets: ["CODE_SERVER_PASSWORD"],
    note: "Log in with CODE_SERVER_PASSWORD from .env.",
    image: "lscr.io/linuxserver/code-server:latest", port: [8443, 8443], data: "/config",
    env: { PASSWORD: "${CODE_SERVER_PASSWORD}", DEFAULT_WORKSPACE: "/config/workspace" },
  },
  {
    id: "forgejo", lxc: "forgejo", name: "Forgejo", category: "Dev", difficulty: 2,
    desc: "Community-run Git forge (a Gitea fork) with issues, PRs and Actions.",
    docs: "https://forgejo.org/docs/latest/admin/installation/docker/",
    note: "In the install wizard, set the base URL to this server's address and port 3011, and the SSH port to 2223.",
    image: "codeberg.org/forgejo/forgejo:11", data: "/data",
    ports: [{ host: 3011, container: 3000, label: "Web UI" }, { host: 2223, container: 22, label: "Git over SSH" }],
    env: { USER_UID: "${PUID}", USER_GID: "${PGID}" },
    volumes: ["/etc/localtime:/etc/localtime:ro"],
  },
  {
    id: "gitlab", lxc: "gitlab", name: "GitLab CE", category: "Dev", difficulty: 3,
    desc: "Full DevOps platform: Git, CI/CD, registry, issues. Needs 4 GB+ RAM.",
    docs: "https://docs.gitlab.com/install/docker/",
    note: "First start takes several minutes. The root password is in <config folder>/gitlab/config/initial_root_password.",
    image: "gitlab/gitlab-ce:latest",
    ports: [{ host: 8119, container: 80, label: "Web UI" }, { host: 2224, container: 22, label: "Git over SSH" }],
    env: { GITLAB_OMNIBUS_CONFIG: "gitlab_rails['gitlab_shell_ssh_port'] = 2224" },
    volumes: ["${CONFIG_ROOT}/gitlab/config:/etc/gitlab", "${CONFIG_ROOT}/gitlab/logs:/var/log/gitlab", "${CONFIG_ROOT}/gitlab/data:/var/opt/gitlab"],
  },
  {
    id: "jenkins", lxc: "jenkins", name: "Jenkins", category: "Dev", difficulty: 3,
    desc: "Classic automation server for builds and CI/CD pipelines.",
    docs: "https://www.jenkins.io/doc/book/installing/docker/",
    note: "Folder must be owned by user 1000. The unlock password is in the logs: docker logs jenkins",
    image: "jenkins/jenkins:lts", data: "/var/jenkins_home",
    ports: [{ host: 8117, container: 8080, label: "Web UI" }, { host: 50000, container: 50000, label: "Agents" }],
  },
  {
    id: "registry", name: "Docker Registry", category: "Dev", difficulty: 2,
    desc: "Private registry to push and pull your own container images.",
    docs: "https://distribution.github.io/distribution/",
    note: "Plain HTTP: add <server-ip>:5002 to insecure-registries on your Docker clients, or put it behind HTTPS.",
    image: "registry:3", port: [5002, 5000, { label: "API" }], data: "/var/lib/registry",
  },
  {
    id: "adminer", name: "Adminer", category: "Dev", difficulty: 2,
    desc: "One-page database admin for MySQL, PostgreSQL, SQLite and more.",
    docs: "https://www.adminer.org/",
    note: "Use the database service name (e.g. nextcloud-db) as the server.",
    image: "adminer:latest", port: [8118, 8080],
  },
  {
    id: "pgadmin", name: "pgAdmin", category: "Dev", difficulty: 2,
    desc: "Full-featured PostgreSQL admin tool.",
    docs: "https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html",
    secrets: ["PGADMIN_PASSWORD"],
    vars: { PGADMIN_EMAIL: { value: "admin@example.com", help: "Your pgAdmin login email" } },
    note: "Folder must be owned by user 5050: sudo chown -R 5050:5050 <config folder>/pgadmin",
    image: "dpage/pgadmin4:latest", port: [5050, 80], data: "/var/lib/pgadmin",
    env: { PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}", PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}" },
  },
  {
    id: "mailpit", lxc: "mailpit", name: "Mailpit", category: "Dev", difficulty: 2,
    desc: "Catches all email your apps send so you can read it in a web inbox. Great for testing.",
    docs: "https://mailpit.axllent.org/docs/",
    note: "Point apps' SMTP settings at mailpit:1025 (inside the stack) or <server-ip>:1025.",
    image: "axllent/mailpit:latest", data: "/data",
    ports: [{ host: 8025, container: 8025, label: "Web UI" }, { host: 1025, container: 1025, label: "SMTP" }],
    env: { MP_DATABASE: "/data/mailpit.db", TZ: "${TZ}" },
  },
  {
    id: "jupyter", lxc: "jupyternotebook", name: "JupyterLab", category: "Dev", difficulty: 2,
    desc: "Python notebooks in the browser with the scientific stack preinstalled.",
    docs: "https://jupyter-docker-stacks.readthedocs.io/",
    secrets: ["JUPYTER_TOKEN"],
    note: "Log in with JUPYTER_TOKEN from .env.",
    image: "quay.io/jupyter/scipy-notebook:latest", port: [8889, 8888],
    env: { JUPYTER_TOKEN: "${JUPYTER_TOKEN}" },
    volumes: ["${CONFIG_ROOT}/jupyter:/home/jovyan/work"],
  },
  {
    id: "rustdesk", lxc: "rustdeskserver", name: "RustDesk Server", category: "Network", difficulty: 2,
    desc: "Your own relay for RustDesk remote desktop (a TeamViewer/AnyDesk alternative).",
    docs: "https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/",
    note: "In RustDesk clients, set the ID server to this server's IP and paste the key from <config folder>/rustdesk/id_ed25519.pub.",
    services: [
      {
        name: "hbbs", image: "rustdesk/rustdesk-server:latest", command: "hbbs", hostNetwork: true,
        ports: [
          { host: 21115, container: 21115, label: "NAT test" },
          { host: 21116, container: 21116, label: "ID (TCP)" },
          { host: 21116, container: 21116, proto: "udp", label: "ID (UDP)" },
          { host: 21118, container: 21118, label: "Web client" },
        ],
        volumes: ["${CONFIG_ROOT}/rustdesk:/root"],
        depends: ["hbbr"],
      },
      {
        name: "hbbr", image: "rustdesk/rustdesk-server:latest", command: "hbbr", hostNetwork: true,
        ports: [{ host: 21117, container: 21117, label: "Relay" }, { host: 21119, container: 21119, label: "Web relay" }],
        volumes: ["${CONFIG_ROOT}/rustdesk:/root"],
      },
    ],
  },
  {
    id: "netbootxyz", lxc: "netboot-xyz", name: "netboot.xyz", category: "Network", difficulty: 3,
    desc: "Boot and install dozens of operating systems over the network (PXE).",
    docs: "https://netboot.xyz/docs/docker",
    note: "Point your router's DHCP next-server/TFTP option at this server.",
    image: "ghcr.io/netbootxyz/netbootxyz:latest", data: "/config",
    ports: [
      { host: 3013, container: 3000, label: "Web UI" },
      { host: 69, container: 69, proto: "udp", label: "TFTP", fixed: true },
      { host: 8128, container: 80, label: "Assets" },
    ],
    volumes: ["${CONFIG_ROOT}/netbootxyz-assets:/assets"],
  },

  // ---------- AI ----------
  {
    id: "anythingllm", name: "AnythingLLM", category: "AI", difficulty: 2,
    desc: "Chat with your documents using local (Ollama) or cloud AI models.",
    docs: "https://docs.anythingllm.com/installation-docker/overview",
    note: "Folder must be owned by user 1000. To use Ollama from this stack, set the base URL to http://ollama:11434.",
    image: "mintplexlabs/anythingllm:latest", port: [3012, 3001], data: "/app/server/storage", capAdd: ["SYS_ADMIN"],
    env: { STORAGE_DIR: "/app/server/storage" },
  },
  {
    id: "searxng", lxc: "searxng", name: "SearXNG", category: "AI", difficulty: 2,
    desc: "Private metasearch engine: Google/Bing/DDG results without tracking.",
    docs: "https://docs.searxng.org/admin/installation-docker.html",
    secrets: ["SEARXNG_SECRET"],
    image: "searxng/searxng:latest", port: [8120, 8080], data: "/etc/searxng",
    env: { SEARXNG_SECRET: "${SEARXNG_SECRET}" },
  },

  // ---------- Smart home ----------
  {
    id: "mosquitto", lxc: "mqtt", name: "Mosquitto (MQTT)", category: "Smart Home", difficulty: 2,
    desc: "MQTT message broker that Zigbee2MQTT, Tasmota and ESPHome devices talk through.",
    docs: "https://mosquitto.org/documentation/",
    note: "Create <config folder>/mosquitto/config/mosquitto.conf containing 'listener 1883' and 'allow_anonymous true' (or set up a password file), or it only accepts local connections.",
    image: "eclipse-mosquitto:2",
    ports: [{ host: 1883, container: 1883, label: "MQTT" }],
    volumes: ["${CONFIG_ROOT}/mosquitto/config:/mosquitto/config", "${CONFIG_ROOT}/mosquitto/data:/mosquitto/data", "${CONFIG_ROOT}/mosquitto/log:/mosquitto/log"],
  },
  {
    id: "zigbee2mqtt", lxc: "zigbee2mqtt", name: "Zigbee2MQTT", category: "Smart Home", difficulty: 3, requires: ["mosquitto"],
    desc: "Use Zigbee devices from any brand without their hubs. Needs a USB Zigbee adapter.",
    docs: "https://www.zigbee2mqtt.io/guide/installation/02_docker.html",
    vars: { ZIGBEE_ADAPTER: { value: "/dev/serial/by-id/CHANGE-ME", help: "Your adapter's path: run ls -l /dev/serial/by-id/" } },
    note: "Set ZIGBEE_ADAPTER in .env. In the onboarding page, use mqtt://mosquitto:1883 as the MQTT server.",
    image: "ghcr.io/koenkk/zigbee2mqtt:latest", port: [8121, 8080], data: "/app/data",
    env: { TZ: "${TZ}" },
    devices: ["${ZIGBEE_ADAPTER}:/dev/ttyACM0"],
    volumes: ["/run/udev:/run/udev:ro"],
  },
  {
    id: "esphome", lxc: "esphome", name: "ESPHome", category: "Smart Home", difficulty: 2,
    desc: "Build your own sensors and smart devices from cheap ESP32 boards, with YAML.",
    docs: "https://esphome.io/guides/getting_started_command_line",
    image: "ghcr.io/esphome/esphome:latest", hostNetwork: true, data: "/config",
    ports: [{ host: 6052, container: 6052, label: "Web UI" }],
    env: { TZ: "${TZ}" },
  },
  {
    id: "homebridge", lxc: "homebridge", name: "Homebridge", category: "Smart Home", difficulty: 1,
    desc: "Adds non-HomeKit devices to Apple Home.",
    docs: "https://github.com/homebridge/docker-homebridge/wiki",
    image: "homebridge/homebridge:latest", hostNetwork: true,
    ports: [{ host: 8581, container: 8581, label: "Web UI" }],
    volumes: ["${CONFIG_ROOT}/homebridge:/homebridge"],
  },
  {
    id: "matterserver", lxc: "matter-server", name: "Matter Server", category: "Smart Home", difficulty: 3,
    desc: "Lets Home Assistant control Matter devices.",
    docs: "https://github.com/home-assistant-libs/python-matter-server",
    note: "In Home Assistant, add the Matter integration and use ws://localhost:5580/ws.",
    image: "ghcr.io/home-assistant-libs/python-matter-server:stable", hostNetwork: true, data: "/data",
    ports: [{ host: 5580, container: 5580, label: "API" }],
    volumes: ["/run/dbus:/run/dbus:ro"],
  },
  {
    id: "nodered", lxc: "node-red", name: "Node-RED", category: "Smart Home", difficulty: 2,
    desc: "Wire together devices, APIs and automations visually. Popular with Home Assistant.",
    docs: "https://nodered.org/docs/getting-started/docker",
    note: "Runs as user 1000: sudo chown -R 1000:1000 <config folder>/nodered",
    image: "nodered/node-red:latest", port: [1880, 1880], data: "/data",
    env: { TZ: "${TZ}" },
  },
  {
    id: "whisper", name: "Whisper (speech-to-text)", category: "Smart Home", difficulty: 3, lsio: true,
    desc: "Local speech recognition for Home Assistant's voice assistant (Wyoming protocol).",
    docs: "https://docs.linuxserver.io/images/docker-faster-whisper/",
    note: "In Home Assistant, add the Wyoming integration pointing at <server-ip>:10300.",
    image: "lscr.io/linuxserver/faster-whisper:latest", data: "/config",
    ports: [{ host: 10300, container: 10300, label: "Wyoming" }],
    env: { WHISPER_MODEL: "tiny-int8", WHISPER_LANG: "en" },
  },
  {
    id: "piper", name: "Piper (text-to-speech)", category: "Smart Home", difficulty: 3, lsio: true,
    desc: "Local, natural-sounding voices for Home Assistant's voice assistant.",
    docs: "https://docs.linuxserver.io/images/docker-piper/",
    note: "In Home Assistant, add the Wyoming integration pointing at <server-ip>:10200.",
    image: "lscr.io/linuxserver/piper:latest", data: "/config",
    ports: [{ host: 10200, container: 10200, label: "Wyoming" }],
    env: { PIPER_VOICE: "en_US-lessac-medium" },
  },
  {
    id: "frigate", lxc: "frigate", name: "Frigate", category: "Smart Home", difficulty: 3,
    desc: "Security camera NVR with AI object detection (people, cars, animals).",
    docs: "https://docs.frigate.video/",
    composeUrl: "https://docs.frigate.video/frigate/installation#docker",
    note: "Needs camera config and ideally a Coral or GPU detector. Use the official install guide.",
  },

  // ---------- Games ----------
  {
    id: "minecraft", name: "Minecraft Server", category: "Games", difficulty: 1,
    desc: "Java Edition server (Paper) for you and your friends.",
    docs: "https://docker-minecraft-server.readthedocs.io/",
    note: "EULA=TRUE means you accept Minecraft's EULA. Change MEMORY to fit your server. Connect to <server-ip>:25565.",
    image: "itzg/minecraft-server:latest", data: "/data",
    ports: [{ host: 25565, container: 25565, label: "Game" }],
    env: { EULA: "TRUE", TYPE: "PAPER", MEMORY: "4G", TZ: "${TZ}" },
  },
  {
    id: "valheim", name: "Valheim Server", category: "Games", difficulty: 2,
    desc: "Dedicated Valheim server with automatic updates and backups.",
    docs: "https://github.com/lloesche/valheim-server-docker",
    secrets: ["VALHEIM_PASSWORD"],
    note: "The join password is VALHEIM_PASSWORD in .env. Forward UDP 2456-2457 to play outside your home.",
    image: "ghcr.io/lloesche/valheim-server:latest", capAdd: ["SYS_NICE"],
    ports: [
      { host: 2456, container: 2456, proto: "udp", label: "Game" },
      { host: 2457, container: 2457, proto: "udp", label: "Query" },
    ],
    env: { SERVER_NAME: "My Valheim Server", WORLD_NAME: "Dedicated", SERVER_PASS: "${VALHEIM_PASSWORD}", SERVER_PUBLIC: "false", TZ: "${TZ}" },
    volumes: ["${CONFIG_ROOT}/valheim/config:/config", "${CONFIG_ROOT}/valheim/server:/opt/valheim"],
  },
);
